import { NextRequest, NextResponse } from "next/server";
import { pumpManager } from "@/storage/database/pumpManager";

const pumpData = [
  // 卧式多级离心泵系列（大流量）
  {
    name: "卧式多级离心泵D系列",
    model: "D50-60",
    brand: "洛瓦托",
    pumpType: "卧式多级离心泵",
    material: "不锈钢",
    flowRate: 50,
    head: 60,
    power: 18.5,
    efficiency: 78,
    speed: 2900,
    inletDiameter: 100,
    outletDiameter: 80,
    maxTemperature: 80,
    maxPressure: 16,
    applicationType: "消防系统",
    description: "大流量多级离心泵，适用于消防系统供水",
  },
  {
    name: "卧式多级离心泵D系列",
    model: "D80-50",
    brand: "洛瓦托",
    pumpType: "卧式多级离心泵",
    material: "不锈钢",
    flowRate: 80,
    head: 50,
    power: 22,
    efficiency: 80,
    speed: 2900,
    inletDiameter: 125,
    outletDiameter: 100,
    maxTemperature: 80,
    maxPressure: 16,
    applicationType: "消防系统",
    description: "大流量多级离心泵，适用于消防系统供水",
  },
  {
    name: "卧式多级离心泵D系列",
    model: "D100-40",
    brand: "洛瓦托",
    pumpType: "卧式多级离心泵",
    material: "铸铁",
    flowRate: 100,
    head: 40,
    power: 22,
    efficiency: 79,
    speed: 2950,
    inletDiameter: 150,
    outletDiameter: 125,
    maxTemperature: 80,
    maxPressure: 16,
    applicationType: "市政供水",
    description: "大流量多级离心泵，适用于市政供水系统",
  },
  {
    name: "卧式多级离心泵D系列",
    model: "D150-60",
    brand: "洛瓦托",
    pumpType: "卧式多级离心泵",
    material: "铸铁",
    flowRate: 150,
    head: 60,
    power: 45,
    efficiency: 81,
    speed: 2950,
    inletDiameter: 200,
    outletDiameter: 150,
    maxTemperature: 80,
    maxPressure: 16,
    applicationType: "市政供水",
    description: "大流量多级离心泵，适用于市政供水系统",
  },

  // 立式多级离心泵系列
  {
    name: "立式多级离心泵CDL系列",
    model: "CDL8-12",
    brand: "洛瓦托",
    pumpType: "立式多级离心泵",
    material: "不锈钢",
    flowRate: 8,
    head: 12,
    power: 1.5,
    efficiency: 72,
    speed: 2900,
    inletDiameter: 50,
    outletDiameter: 32,
    maxTemperature: 80,
    maxPressure: 16,
    applicationType: "供水系统",
    description: "立式多级离心泵，适用于供水系统",
  },
  {
    name: "立式多级离心泵CDL系列",
    model: "CDL16-15",
    brand: "洛瓦托",
    pumpType: "立式多级离心泵",
    material: "不锈钢",
    flowRate: 16,
    head: 15,
    power: 3,
    efficiency: 74,
    speed: 2900,
    inletDiameter: 65,
    outletDiameter: 40,
    maxTemperature: 80,
    maxPressure: 16,
    applicationType: "供水系统",
    description: "立式多级离心泵，适用于供水系统",
  },
  {
    name: "立式多级离心泵CDL系列",
    model: "CDL32-30",
    brand: "洛瓦托",
    pumpType: "立式多级离心泵",
    material: "不锈钢",
    flowRate: 32,
    head: 30,
    power: 7.5,
    efficiency: 76,
    speed: 2900,
    inletDiameter: 80,
    outletDiameter: 50,
    maxTemperature: 80,
    maxPressure: 25,
    applicationType: "建筑供水",
    description: "立式多级离心泵，适用于建筑供水",
  },
  {
    name: "立式多级离心泵CDL系列",
    model: "CDL50-50",
    brand: "洛瓦托",
    pumpType: "立式多级离心泵",
    material: "不锈钢",
    flowRate: 50,
    head: 50,
    power: 15,
    efficiency: 78,
    speed: 2900,
    inletDiameter: 100,
    outletDiameter: 65,
    maxTemperature: 80,
    maxPressure: 25,
    applicationType: "建筑供水",
    description: "立式多级离心泵，适用于建筑供水",
  },

  // 立式单级管道泵系列
  {
    name: "立式单级管道泵ISG系列",
    model: "ISG50-125",
    brand: "洛瓦托",
    pumpType: "立式单级管道泵",
    material: "不锈钢",
    flowRate: 12.5,
    head: 20,
    power: 2.2,
    efficiency: 68,
    speed: 2900,
    inletDiameter: 50,
    outletDiameter: 50,
    maxTemperature: 80,
    maxPressure: 16,
    applicationType: "暖通空调",
    description: "立式单级管道泵，适用于暖通空调系统",
  },
  {
    name: "立式单级管道泵ISG系列",
    model: "ISG65-160",
    brand: "洛瓦托",
    pumpType: "立式单级管道泵",
    material: "不锈钢",
    flowRate: 25,
    head: 32,
    power: 5.5,
    efficiency: 71,
    speed: 2900,
    inletDiameter: 65,
    outletDiameter: 65,
    maxTemperature: 80,
    maxPressure: 16,
    applicationType: "暖通空调",
    description: "立式单级管道泵，适用于暖通空调系统",
  },
  {
    name: "立式单级管道泵ISG系列",
    model: "ISG80-200",
    brand: "洛瓦托",
    pumpType: "立式单级管道泵",
    material: "不锈钢",
    flowRate: 50,
    head: 50,
    power: 15,
    efficiency: 74,
    speed: 2900,
    inletDiameter: 80,
    outletDiameter: 80,
    maxTemperature: 80,
    maxPressure: 16,
    applicationType: "供水系统",
    description: "立式单级管道泵，适用于供水系统",
  },
  {
    name: "立式单级管道泵ISG系列",
    model: "ISG100-250",
    brand: "洛瓦托",
    pumpType: "立式单级管道泵",
    material: "铸铁",
    flowRate: 100,
    head: 80,
    power: 37,
    efficiency: 76,
    speed: 2900,
    inletDiameter: 100,
    outletDiameter: 100,
    maxTemperature: 80,
    maxPressure: 16,
    applicationType: "工业循环",
    description: "立式单级管道泵，适用于工业循环系统",
  },

  // 卧式单级端吸泵系列
  {
    name: "卧式单级端吸泵IS系列",
    model: "IS50-32-160",
    brand: "洛瓦托",
    pumpType: "卧式单级端吸泵",
    material: "不锈钢",
    flowRate: 12.5,
    head: 32,
    power: 3,
    efficiency: 69,
    speed: 2900,
    inletDiameter: 50,
    outletDiameter: 32,
    maxTemperature: 80,
    maxPressure: 16,
    applicationType: "化工流程",
    description: "卧式单级端吸泵，适用于化工流程",
  },
  {
    name: "卧式单级端吸泵IS系列",
    model: "IS65-50-200",
    brand: "洛瓦托",
    pumpType: "卧式单级端吸泵",
    material: "不锈钢",
    flowRate: 25,
    head: 50,
    power: 7.5,
    efficiency: 72,
    speed: 2900,
    inletDiameter: 65,
    outletDiameter: 50,
    maxTemperature: 80,
    maxPressure: 16,
    applicationType: "化工流程",
    description: "卧式单级端吸泵，适用于化工流程",
  },
  {
    name: "卧式单级端吸泵IS系列",
    model: "IS80-65-250",
    brand: "洛瓦托",
    pumpType: "卧式单级端吸泵",
    material: "铸铁",
    flowRate: 50,
    head: 80,
    power: 22,
    efficiency: 75,
    speed: 2900,
    inletDiameter: 80,
    outletDiameter: 65,
    maxTemperature: 80,
    maxPressure: 16,
    applicationType: "工业循环",
    description: "卧式单级端吸泵，适用于工业循环",
  },
  {
    name: "卧式单级端吸泵IS系列",
    model: "IS100-80-315",
    brand: "洛瓦托",
    pumpType: "卧式单级端吸泵",
    material: "铸铁",
    flowRate: 100,
    head: 125,
    power: 75,
    efficiency: 77,
    speed: 2900,
    inletDiameter: 100,
    outletDiameter: 80,
    maxTemperature: 80,
    maxPressure: 25,
    applicationType: "工业循环",
    description: "卧式单级端吸泵，适用于工业循环",
  },

  // 增压泵系列
  {
    name: "卧式多级离心增压泵DZ系列",
    model: "DZ10-12",
    brand: "洛瓦托",
    pumpType: "卧式多级离心增压泵",
    material: "不锈钢",
    flowRate: 10,
    head: 12,
    power: 1.5,
    efficiency: 70,
    speed: 2900,
    inletDiameter: 50,
    outletDiameter: 32,
    maxTemperature: 80,
    maxPressure: 16,
    applicationType: "建筑供水",
    description: "多级离心增压泵，适用于建筑供水增压",
  },
  {
    name: "立式多级离心增压泵CDLF系列",
    model: "CDLF16-20",
    brand: "洛瓦托",
    pumpType: "立式多级离心增压泵",
    material: "不锈钢",
    flowRate: 16,
    head: 20,
    power: 2.2,
    efficiency: 72,
    speed: 2900,
    inletDiameter: 50,
    outletDiameter: 40,
    maxTemperature: 80,
    maxPressure: 16,
    applicationType: "建筑供水",
    description: "立式多级离心增压泵，适用于建筑供水增压",
  },
  {
    name: "立式单级管道增压泵ISGF系列",
    model: "ISGF25-160",
    brand: "洛瓦托",
    pumpType: "立式单级管道增压泵",
    material: "不锈钢",
    flowRate: 5,
    head: 8,
    power: 0.75,
    efficiency: 65,
    speed: 2900,
    inletDiameter: 25,
    outletDiameter: 25,
    maxTemperature: 80,
    maxPressure: 10,
    applicationType: "深井取水",
    description: "立式单级管道增压泵，适用于深井取水",
  },

  // 变频增压泵系列
  {
    name: "卧式多级离心变频增压泵DV系列",
    model: "DV20-30",
    brand: "洛瓦托",
    pumpType: "卧式多级离心变频增压泵",
    material: "不锈钢",
    flowRate: 20,
    head: 30,
    power: 5.5,
    efficiency: 74,
    speed: 2900,
    inletDiameter: 65,
    outletDiameter: 40,
    maxTemperature: 80,
    maxPressure: 16,
    applicationType: "建筑供水",
    description: "变频增压泵，适用于建筑供水变频控制",
  },
  {
    name: "立式多级离心变频增压泵CDLVF系列",
    model: "CDLVF32-40",
    brand: "洛瓦托",
    pumpType: "立式多级离心变频增压泵",
    material: "不锈钢",
    flowRate: 32,
    head: 40,
    power: 7.5,
    efficiency: 76,
    speed: 2900,
    inletDiameter: 80,
    outletDiameter: 50,
    maxTemperature: 80,
    maxPressure: 16,
    applicationType: "建筑供水",
    description: "变频增压泵，适用于建筑供水变频控制",
  },
  {
    name: "立式单级管道变频增压泵ISGVF系列",
    model: "ISGVF50-200",
    brand: "洛瓦托",
    pumpType: "立式单级管道变频增压泵",
    material: "不锈钢",
    flowRate: 50,
    head: 50,
    power: 15,
    efficiency: 74,
    speed: 2900,
    inletDiameter: 100,
    outletDiameter: 65,
    maxTemperature: 80,
    maxPressure: 16,
    applicationType: "建筑供水",
    description: "变频增压泵，适用于建筑供水变频控制",
  },

  // 家用变频增压泵
  {
    name: "家用变频增压泵PB系列",
    model: "PB-550",
    brand: "洛瓦托",
    pumpType: "家用变频增压泵",
    material: "不锈钢",
    flowRate: 5,
    head: 15,
    power: 0.55,
    efficiency: 60,
    speed: 2800,
    inletDiameter: 25,
    outletDiameter: 25,
    maxTemperature: 60,
    maxPressure: 10,
    applicationType: "深井取水",
    description: "家用变频增压泵，适用于家庭供水增压",
  },
  {
    name: "家用变频增压泵PB系列",
    model: "PB-750",
    brand: "洛瓦托",
    pumpType: "家用变频增压泵",
    material: "不锈钢",
    flowRate: 8,
    head: 20,
    power: 0.75,
    efficiency: 62,
    speed: 2800,
    inletDiameter: 32,
    outletDiameter: 25,
    maxTemperature: 60,
    maxPressure: 10,
    applicationType: "地下水抽取",
    description: "家用变频增压泵，适用于家庭供水增压",
  },

  // 工频屏蔽泵
  {
    name: "工频屏蔽泵CQ系列",
    model: "CQ15-50",
    brand: "洛瓦托",
    pumpType: "工频屏蔽泵",
    material: "不锈钢",
    flowRate: 15,
    head: 50,
    power: 5.5,
    efficiency: 70,
    speed: 2900,
    inletDiameter: 65,
    outletDiameter: 40,
    maxTemperature: 80,
    maxPressure: 16,
    applicationType: "化工流程",
    description: "工频屏蔽泵，适用于化工流程输送",
  },
  {
    name: "工频屏蔽泵CQ系列",
    model: "CQ25-80",
    brand: "洛瓦托",
    pumpType: "工频屏蔽泵",
    material: "不锈钢",
    flowRate: 25,
    head: 80,
    power: 11,
    efficiency: 72,
    speed: 2900,
    inletDiameter: 80,
    outletDiameter: 50,
    maxTemperature: 80,
    maxPressure: 16,
    applicationType: "化工流程",
    description: "工频屏蔽泵，适用于化工流程输送",
  },
];

export async function POST(request: NextRequest) {
  try {
    let success = 0;
    let failed = 0;
    const errors: string[] = [];

    for (const pump of pumpData) {
      try {
        await pumpManager.createPump(pump);
        success++;
      } catch (error) {
        failed++;
        const errorMsg = error instanceof Error ? error.message : String(error);
        errors.push(`${pump.model}: ${errorMsg}`);
        console.error(`导入失败: ${pump.model}`, error);
      }
    }

    return NextResponse.json({
      success: true,
      message: "产品库数据初始化完成",
      result: {
        total: pumpData.length,
        success,
        failed,
        errors,
      },
    });
  } catch (error) {
    console.error("Error seeding pumps:", error);
    return NextResponse.json(
      { error: "Failed to seed pumps", details: error instanceof Error ? error.message : String(error) },
      { status: 500 }
    );
  }
}
